#     ___ ___             __                  __    __ __ 
#    |   Y   .--.--.-----|  |_.-----.----.   |  |--|__|  |_.----.-----.
#    |.  |   |  |  |     |   _|  -__|   _|   |    <|  |   _|   _|  _  |
#    |. / \  |___  |__|__|____|_____|__|     |__|__|__|____|__| |_____|
#    |:      |_____|
#    |::.|:. |       Dereckson's $HOME/bin personal collection
#    `--- ---'       Wynter-kitro edition

INSTALL=/usr/bin/install
PREFIX?=${HOME}

make:

make install:
	${INSTALL} git-bye.sh ${PREFIX}/bin/git-bye
	${INSTALL} git-newbug.sh ${PREFIX}/bin/git-newbug
	${INSTALL} update-git-prompt.csh ${PREFIX}/bin/update-git-prompt
