#     ___ ___             __                  __    __ __ 
#    |   Y   .--.--.-----|  |_.-----.----.   |  |--|__|  |_.----.-----.
#    |.  |   |  |  |     |   _|  -__|   _|   |    <|  |   _|   _|  _  |
#    |. / \  |___  |__|__|____|_____|__|     |__|__|__|____|__| |_____|
#    |:      |_____|
#    |::.|:. |       Dereckson's $HOME/bin personal collection
#    `--- ---'       Wynter-kitro edition

INSTALL=/usr/bin/install
PREFIX?=${HOME}

make:

make install:
	${INSTALL} port-patches-generator.tcl ${PREFIX}/bin/port-patches-generator
