#     ___ ___             __                  __    __ __ 
#    |   Y   .--.--.-----|  |_.-----.----.   |  |--|__|  |_.----.-----.
#    |.  |   |  |  |     |   _|  -__|   _|   |    <|  |   _|   _|  _  |
#    |. / \  |___  |__|__|____|_____|__|     |__|__|__|____|__| |_____|
#    |:      |_____|
#    |::.|:. |       Dereckson's $HOME/bin personal collection
#    `--- ---'       Wynter-kitro edition

INSTALL=/usr/bin/install
PREFIX?=${HOME}

make:

make install:
	${INSTALL} arc-paste-diff.sh ${PREFIX}/bin/arc-paste-diff
	${INSTALL} arc-paste-file.sh ${PREFIX}/bin/arc-paste-file
	${INSTALL} arc-update-repo.sh ${PREFIX}/bin/arc-update-repo
